version: 2.1
orbs:
  node: circleci/node@1.1.6
  win: circleci/windows@2.2.0
jobs:
  build_linux:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo npm install -g n
            - run: sudo n 11.10.1
            - run: sudo apt-get update
            - run: sudo apt-get install -y g++ gcc make python2.7 pkg-config libx11-dev libxkbfile-dev
            - run: sudo apt-get install libsecret-1-dev
            - run: sudo apt-get install fakeroot rpm
            - run: sudo npm install -g node-gyp
            - run: sudo npm install yarn -g
            - run: sudo yarn
            - run: sudo yarn add node-abi@2.15.0
            - run: sudo yarn add electron-builder --dev
            - run: chmod +x ./scripts/code.sh
            - run:
                command: sudo bash ./scripts/code.sh
                when: always
            - run: 
                command: sudo yarn run dist --linux
                when: always
            - run: sudo git clone https://github.com/cactiva/release
            - run: sudo cd release
            - run: sudo cp dist/Cactiva.deb
            - run: sudo git add Cactiva.deb .
            - run: sudo cp dist/Cactiva.rpm
            - run: sudo git add Cactiva.rpm .
            - run: sudo git commit -m "build dari circleci"
            - run: git push
            - store_artifacts:
                path: /home/circleci/project/dist/
  
  build_windows:
    executor: win/default
    steps:
      - checkout
      - run: 
          command: cd project
          shell: cmd.exe
      - run: 
          command: npm install yarn -g
          shell: cmd.exe
      - run: 
          command: yarn --frozen-lockfile
          shell: cmd.exe
      - run: 
          command: yarn add electron-builder --dev
          shell: cmd.exe
      - run: 
          command: yarn watch
          shell: cmd.exe
      - run: 
          command: C:\Program Files\project\scripts\code.bat
          shell: cmd.exe
          when: always
      - run: 
          command: yarn run dist --win
          shell: cmd.exe
          when: always
      - store_artifacts:
          path: dist\

  build_macos:
      macos:
        xcode: "11.3.0"
      steps:
       - checkout
       - run: sudo npm install -g n
       - run: sudo n 11.10.1
       - run: sudo yarn 
       - run: sudo yarn add electron-builder --dev
       - run: sudo ./scripts/code.sh
       - run: 
           command: sudo yarn run dist --mac
           when: always
       - run: sudo git clone https://github.com/cactiva/release
       - run: sudo cd release
       - run: sudo cp dist/Cactiva.dmg
       - run: sudo git add Cactiva.dmg .
       - run: sudo git commit -m "Macos, build dari circleci"
       - run: git push
       - store_artifacts:
            path: dist/Cactiva.dmg
  
workflows:
    build-and-test:
      jobs:
        - build_linux
        - build_macos
