version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo npm install -g n
            - run: sudo n 11.10.1
            - run: sudo apt-get update
            - run: sudo apt-get install -y g++ gcc make python2.7 pkg-config libx11-dev libxkbfile-dev
            - run: sudo apt-get install libsecret-1-dev
            - run: sudo apt-get install fakeroot rpm
            - run: sudo npm install node-abi -g
            - run: sudo npm install -g node-gyp
            - run: sudo npm install yarn -g
            - run: yarn
            - run: yarn add electron-builder --dev
            - run: yarn run dist
workflows:
    build-and-test:
      jobs:
        - build-and-test
